/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { BiographyWithEntities } from './BiographyWithEntities';
import type { BioLink } from './BioLink';
import type { EdgeFelixVideoTimeline } from './EdgeFelixVideoTimeline';
import type { EdgeFollow } from './EdgeFollow';
import type { EdgeFollowedBy } from './EdgeFollowedBy';
import type { EdgeMediaCollections } from './EdgeMediaCollections';
import type { EdgeMutualFollowedBy } from './EdgeMutualFollowedBy';
import type { EdgeOwnerToTimelineMedia } from './EdgeOwnerToTimelineMedia';
import type { EdgeRelatedProfiles } from './EdgeRelatedProfiles';
import type { EdgeSavedMedia } from './EdgeSavedMedia';
export type InstagramDL__models__User__User = {
    ai_agent_type?: null;
    biography?: string;
    bio_links?: Array<BioLink>;
    fb_profile_biolink?: null;
    biography_with_entities?: BiographyWithEntities;
    blocked_by_viewer?: boolean;
    restricted_by_viewer?: boolean;
    country_block?: boolean;
    eimu_id?: string;
    external_url?: string;
    external_url_linkshimmed?: string;
    edge_followed_by?: EdgeFollowedBy;
    fbid?: string;
    followed_by_viewer?: boolean;
    edge_follow?: EdgeFollow;
    follows_viewer?: boolean;
    full_name?: string;
    group_metadata?: null;
    has_ar_effects?: boolean;
    has_clips?: boolean;
    has_guides?: boolean;
    has_channel?: boolean;
    has_blocked_viewer?: boolean;
    highlight_reel_count?: number;
    has_requested_viewer?: boolean;
    hide_like_and_view_counts?: boolean;
    id?: string;
    is_business_account?: boolean;
    is_professional_account?: boolean;
    is_supervision_enabled?: boolean;
    is_guardian_of_viewer?: boolean;
    is_supervised_by_viewer?: boolean;
    is_supervised_user?: boolean;
    is_embeds_disabled?: boolean;
    is_joined_recently?: boolean;
    guardian_id?: null;
    business_address_json?: null;
    business_contact_method?: string;
    business_email?: null;
    business_phone_number?: null;
    business_category_name?: null;
    overall_category_name?: null;
    category_enum?: null;
    category_name?: string;
    is_private?: boolean;
    is_verified?: boolean;
    is_verified_by_mv4b?: boolean;
    is_regulated_c18?: boolean;
    edge_mutual_followed_by?: EdgeMutualFollowedBy;
    pinned_channels_list_count?: number;
    profile_pic_url?: string;
    profile_pic_url_hd?: string;
    requested_by_viewer?: boolean;
    should_show_category?: boolean;
    should_show_public_contacts?: boolean;
    show_account_transparency_details?: boolean;
    remove_message_entrypoint?: boolean;
    transparency_label?: null;
    transparency_product?: null;
    username?: string;
    connected_fb_page?: null;
    pronouns?: Array<any>;
    edge_felix_video_timeline?: EdgeFelixVideoTimeline;
    edge_owner_to_timeline_media?: EdgeOwnerToTimelineMedia;
    edge_saved_media?: EdgeSavedMedia;
    edge_media_collections?: EdgeMediaCollections;
    edge_related_profiles?: EdgeRelatedProfiles;
};

