/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { EligibleProfileTab } from './EligibleProfileTab';
import type { Partner } from './Partner';
import type { ProfileCover } from './ProfileCover';
export type PinterestDL__models__User__Data = {
    node_id?: string;
    image_small_url?: string;
    instagram_data?: any;
    should_show_messaging?: boolean;
    profile_views?: number;
    explicitly_followed_by_me?: boolean;
    image_large_url?: string;
    is_tastemaker?: boolean;
    native_pin_count?: number;
    show_creator_profile?: boolean;
    profile_reach?: number;
    is_private_profile?: boolean;
    pins_done_count?: number;
    joined_communities_count?: number;
    last_pin_save_time?: string;
    last_name?: string;
    impressum_url?: null;
    profile_cover?: ProfileCover;
    verified_identity?: Record<string, any>;
    storefront_search_enabled?: boolean;
    first_name?: string;
    has_catalog?: boolean;
    indexed?: boolean;
    is_inspirational_merchant?: null;
    domain_verified?: boolean;
    has_shopping_showcase?: boolean;
    domain_url?: string;
    website_url?: string;
    pronouns?: Array<any>;
    is_ads_only_profile?: boolean;
    group_board_count?: number;
    show_discovered_feed?: boolean;
    is_verified_merchant?: boolean;
    listed_website_url?: null;
    username?: string;
    follower_count?: number;
    type?: string;
    full_name?: string;
    image_medium_url?: string;
    about?: string;
    show_engagement_tab?: boolean;
    interest_following_count?: number;
    eligible_profile_tabs?: Array<EligibleProfileTab>;
    show_impressum?: boolean;
    has_showcase?: boolean;
    has_custom_board_sorting_order?: boolean;
    video_pin_count?: number;
    blocked_by_me?: boolean;
    explicit_user_following_count?: number;
    ads_only_profile_site?: null;
    id?: string;
    board_count?: number;
    following_count?: number;
    story_pin_count?: number;
    has_published_pins?: boolean;
    is_primary_website_verified?: boolean;
    profile_discovered_public?: boolean;
    storefront_management_enabled?: boolean;
    partner?: Partner;
    image_xlarge_url?: string;
    is_partner?: boolean;
    should_default_comments_off?: boolean;
    pin_count?: number;
};

