/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { CloseupAttribution } from './CloseupAttribution';
import type { FormattedDescription } from './FormattedDescription';
import type { Images } from './Images';
import type { LinkDomain } from './LinkDomain';
import type { PinJoin } from './PinJoin';
import type { Pinner } from './Pinner';
import type { PinterestDL__models__Post__AggregatedPinData } from './PinterestDL__models__Post__AggregatedPinData';
import type { PinterestDL__models__Post__Board } from './PinterestDL__models__Post__Board';
import type { PinterestDL__models__Post__NativeCreator } from './PinterestDL__models__Post__NativeCreator';
import type { PinterestDL__models__Post__ReactionCounts } from './PinterestDL__models__Post__ReactionCounts';
import type { RichMetadata } from './RichMetadata';
import type { Section } from './Section';
export type PinterestDL__models__Post__Data = {
    pin_join?: PinJoin;
    access?: Array<any>;
    music_attributions?: Array<any>;
    link?: string;
    third_party_pin_owner?: any;
    product_pin_data?: any;
    should_mute?: boolean;
    seo_url?: string;
    promoter?: any;
    tracked_link?: string;
    method?: string;
    shopping_flags?: Array<number>;
    dominant_color?: string;
    tracking_params?: string;
    type?: string;
    via_pinner?: any;
    price_currency?: string;
    reaction_counts?: PinterestDL__models__Post__ReactionCounts;
    domain?: string;
    mobile_link?: any;
    aggregated_pin_data?: PinterestDL__models__Post__AggregatedPinData;
    is_repin?: boolean;
    alt_text?: any;
    formatted_description?: FormattedDescription;
    is_quick_promotable_by_pinner?: boolean;
    videos?: any;
    is_native?: boolean;
    media_attribution?: any;
    category?: string;
    embed?: any;
    images?: Images;
    pinner?: Pinner;
    promoted_is_removable?: boolean;
    creator_class?: any;
    link_domain?: LinkDomain;
    sponsorship?: any;
    closeup_description?: string;
    should_open_in_stream?: boolean;
    seo_description?: string;
    pinned_to_board?: any;
    share_count?: number;
    is_promotable?: boolean;
    shopping_rec_disabled?: boolean;
    is_quick_promotable?: boolean;
    origin_pinner?: any;
    is_playable?: boolean;
    repin_count?: number;
    is_stale_product?: boolean;
    board?: PinterestDL__models__Post__Board;
    comments_disabled?: boolean;
    is_promoted?: boolean;
    shuffle?: any;
    closeup_attribution?: CloseupAttribution;
    is_video?: boolean;
    creator_class_instance?: any;
    image_medium_url?: string;
    closeup_user_note?: string;
    should_redirect_id_only_url_to_text_url?: boolean;
    id?: string;
    description?: string;
    story_pin_data_id?: any;
    seo_noindex_reason?: any;
    privacy?: string;
    comment_count?: number;
    created_at?: string;
    seo_title?: string;
    is_eligible_for_brand_catalog?: boolean;
    can_delete_did_it_and_comments?: boolean;
    native_creator?: PinterestDL__models__Post__NativeCreator;
    description_html?: string;
    title?: string;
    content_sensitivity?: Record<string, any>;
    rich_metadata?: RichMetadata;
    is_eligible_for_aggregated_comments?: boolean;
    story_pin_data?: any;
    attribution?: any;
    buyable_product_availability?: any;
    grid_title?: string;
    is_eligible_for_pdp?: boolean;
    hashtags?: Array<any>;
    price_value?: number;
    carousel_data?: any;
    section?: Section;
    auto_alt_text?: any;
    image_signature?: string;
    is_hidden?: boolean;
    did_it_disabled?: boolean;
    is_oos_product?: boolean;
    related_article?: Record<string, any>;
    is_whitelisted_for_tried_it?: boolean;
    closeup_unified_description?: string;
};

