/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { AdData } from './AdData';
import type { DatumImages } from './DatumImages';
import type { Embed } from './Embed';
import type { ImageCrop } from './ImageCrop';
import type { PinterestDL__models__Reverse__AggregatedPinData } from './PinterestDL__models__Reverse__AggregatedPinData';
import type { PinterestDL__models__Reverse__Board } from './PinterestDL__models__Reverse__Board';
import type { PinterestDL__models__Reverse__NativeCreator } from './PinterestDL__models__Reverse__NativeCreator';
import type { PinterestDL__models__Reverse__ReactionCounts } from './PinterestDL__models__Reverse__ReactionCounts';
import type { PinterestDL__models__Reverse__Videos } from './PinterestDL__models__Reverse__Videos';
import type { RichSummary } from './RichSummary';
import type { StoryPinData } from './StoryPinData';
export type PinterestReverseData = {
    dominant_color?: string;
    is_unsafe?: boolean;
    is_full_width?: boolean;
    image_square_url?: string;
    share_count?: number;
    done_by_me?: boolean;
    images?: DatumImages;
    is_cpc_ad?: boolean;
    is_whitelisted_for_tried_it?: boolean;
    comment_reply_comment_id?: string;
    image_medium_url?: string;
    promoted_is_removable?: boolean;
    is_eligible_for_pdp_plus?: boolean;
    aggregated_pin_data?: PinterestDL__models__Reverse__AggregatedPinData;
    image_signature?: string;
    title?: string;
    view_tags?: Array<any>;
    created_at?: string;
    reaction_counts?: PinterestDL__models__Reverse__ReactionCounts;
    is_repin?: boolean;
    additional_hide_reasons?: Array<any>;
    is_year_in_preview?: boolean;
    destination_url_type?: number;
    is_shopping_ad?: boolean;
    is_native?: boolean;
    image_crop?: ImageCrop;
    domain?: string;
    is_eligible_for_brand_catalog?: boolean;
    top_interest?: number;
    board?: PinterestDL__models__Reverse__Board;
    tracking_params?: string;
    is_eligible_for_pdp?: boolean;
    pinner?: PinterestDL__models__Reverse__NativeCreator;
    is_unsafe_for_comments?: boolean;
    native_creator?: PinterestDL__models__Reverse__NativeCreator;
    shopping_flags?: Array<any>;
    category?: string;
    is_eligible_for_aggregated_comments?: boolean;
    is_scene?: boolean;
    comment_count?: number;
    is_promoted?: boolean;
    question_comment_id?: string;
    is_ghost?: boolean;
    cacheable_id?: string;
    is_downstream_promotion?: boolean;
    ip_eligible_for_stela?: boolean;
    should_open_in_stream?: boolean;
    ad_match_reason?: number;
    description?: string;
    promoted_is_quiz?: boolean;
    id?: string;
    promoted_is_showcase?: boolean;
    repin_count?: number;
    promoted_is_max_video?: boolean;
    ad_data?: AdData;
    type?: string;
    is_eligible_for_web_closeup?: boolean;
    should_preload?: boolean;
    virtual_try_on_type?: number;
    is_premiere?: boolean;
    is_video?: boolean;
    comments_disabled?: boolean;
    music_attributions?: Array<any>;
    is_stale_product?: boolean;
    is_eligible_for_related_products?: boolean;
    promoted_is_lead_ad?: boolean;
    is_oos_product?: boolean;
    creative_types?: Array<string>;
    grid_title?: string;
    rich_summary?: RichSummary;
    link?: string;
    tracked_link?: string;
    embed?: Embed;
    origin_pinner?: PinterestDL__models__Reverse__NativeCreator;
    story_pin_data?: StoryPinData;
    should_mute?: boolean;
    videos?: PinterestDL__models__Reverse__Videos;
};

