/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export type PinterestDL__models__User__User = {
    node_id?: string;
    is_employee?: boolean;
    opt_in_private_account?: boolean;
    push_package_user_id?: string;
    age_in_years?: number;
    is_candidate_for_parental_control_passcode?: boolean;
    facebook_publish_stream_enabled?: boolean;
    has_quicksave_board?: boolean;
    connected_to_microsoft?: boolean;
    search_privacy_enabled?: boolean;
    domain_verified?: boolean;
    profile_discovered_public?: null;
    twitter_url?: null;
    allow_marketing_cookies?: null;
    verified_user_websites?: Array<any>;
    has_mfa_enabled?: boolean;
    created_at?: string;
    image_small_url?: string;
    image_large_url?: string;
    website_url?: null;
    can_enable_mfa?: boolean;
    is_under_16?: boolean;
    is_ads_only_profile?: boolean;
    exclude_from_search?: boolean;
    parental_control_anonymized_email?: null;
    allow_analytic_cookies?: null;
    allow_personalization_cookies?: null;
    epik?: string;
    country?: string;
    custom_gender?: null;
    is_private_profile?: boolean;
    unverified_phone_country?: null;
    domain_url?: null;
    connected_to_facebook?: boolean;
    allow_switch_between_private_and_public_profile?: boolean;
    gender?: string;
    ip_country?: string;
    can_edit_search_privacy?: boolean;
    ads_only_profile_site?: null;
    id?: string;
    twitter_publish_enabled?: boolean;
    connected_to_google?: boolean;
    is_eligible_for_image_only_grid?: boolean;
    phone_number_end?: string;
    unverified_phone_number?: null;
    is_high_risk?: boolean;
    listed_website_url?: null;
    should_show_messaging?: boolean;
    is_under_18?: boolean;
    image_xlarge_url?: string;
    resurrection_info?: null;
    facebook_id?: string;
    is_any_website_verified?: boolean;
    phone_number?: null;
    verified_identity?: Record<string, any>;
    facebook_timeline_enabled?: boolean;
    full_name?: string;
    phone_country?: null;
    email?: string;
    connected_to_youtube?: boolean;
    has_password?: boolean;
    third_party_marketing_tracking_enabled?: boolean;
    last_name?: string;
    is_write_banned?: boolean;
    connected_to_dropbox?: boolean;
    is_matured_new_user?: boolean;
    nags?: Array<any>;
    verified_domains?: Array<any>;
    username?: string;
    ip_region?: string;
    login_state?: number;
    unverified_phone_number_without_country?: string;
    personalize_from_offsite_browsing?: boolean;
    is_parental_control_passcode_enabled?: boolean;
    connected_to_etsy?: boolean;
    connected_to_instagram?: boolean;
    image_medium_url?: string;
    first_name?: string;
    is_partner?: boolean;
    type?: string;
    gplus_url?: string;
};

