/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { CarouselMedia } from './CarouselMedia';
import type { InstagramDL__models__RawPost__Caption } from './InstagramDL__models__RawPost__Caption';
import type { InstagramDL__models__RawPost__ClipsMetadata } from './InstagramDL__models__RawPost__ClipsMetadata';
import type { InstagramDL__models__RawPost__ImageVersions2 } from './InstagramDL__models__RawPost__ImageVersions2';
import type { InstagramDL__models__RawPost__Owner } from './InstagramDL__models__RawPost__Owner';
import type { InstagramDL__models__RawPost__SharingFrictionInfo } from './InstagramDL__models__RawPost__SharingFrictionInfo';
import type { InstagramDL__models__RawPost__User } from './InstagramDL__models__RawPost__User';
import type { InstagramDL__models__RawPost__VideoVersion } from './InstagramDL__models__RawPost__VideoVersion';
export type RawPost = {
    code?: string;
    pk?: string;
    id?: string;
    ad_id?: any;
    taken_at?: number;
    inventory_source?: any;
    video_versions?: Array<InstagramDL__models__RawPost__VideoVersion>;
    facepile_top_likers?: Array<any>;
    is_dash_eligible?: number;
    number_of_qualities?: number;
    video_dash_manifest?: string;
    image_versions2?: InstagramDL__models__RawPost__ImageVersions2;
    is_paid_partnership?: boolean;
    sponsor_tags?: any;
    original_height?: number;
    original_width?: number;
    organic_tracking_token?: string;
    user?: InstagramDL__models__RawPost__User;
    group?: any;
    comments_disabled?: any;
    like_and_view_counts_disabled?: boolean;
    can_viewer_reshare?: boolean;
    product_type?: string;
    media_type?: number;
    usertags?: any;
    media_overlay_info?: any;
    carousel_media?: Array<CarouselMedia>;
    location?: any;
    has_audio?: boolean;
    clips_metadata?: InstagramDL__models__RawPost__ClipsMetadata;
    clips_attribution_info?: any;
    has_liked?: boolean;
    carousel_parent_id?: any;
    top_likers?: Array<any>;
    like_count?: number;
    view_count?: any;
    owner?: InstagramDL__models__RawPost__Owner;
    social_context?: any;
    saved_collection_ids?: any;
    has_viewer_saved?: any;
    share_urls?: any;
    ig_media_sharing_disabled?: boolean;
    audience?: any;
    visibility?: any;
    feed_demotion_control?: any;
    feed_recs_demotion_control?: any;
    coauthor_producers?: any;
    photo_of_you?: any;
    caption?: InstagramDL__models__RawPost__Caption;
    can_reshare?: any;
    expiring_at?: any;
    link?: any;
    story_cta?: any;
    logging_info_token?: any;
    sharing_friction_info?: InstagramDL__models__RawPost__SharingFrictionInfo;
    carousel_media_count?: any;
    invited_coauthor_producers?: Array<any>;
    can_see_insights_as_brand?: boolean;
    follow_hashtag_info?: any;
    affiliate_info?: any;
    preview?: any;
    comment_count?: number;
    comments?: Array<any>;
    boosted_status?: any;
    boost_unavailable_identifier?: any;
    boost_unavailable_reason?: any;
    caption_is_edited?: boolean;
    main_feed_carousel_starting_media_id?: any;
    commenting_disabled_for_viewer?: any;
    title?: any;
};

